# Generated by Django 5.1.7 on 2025-05-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='touristGuide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='Travel_Application.touristguide'),
        ),
    ]
