# Generated by Django 5.1.7 on 2025-05-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Application', '0002_alter_travel_touristguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
